#基础配置
spring:
 application:
  name: eureka-server
server:
 port: 8002

eureka:
 instance:
  hostname: localhost
 client:
  register-with-eureka: false
  fetch-registry: false
 server:
   #是否开启安全保护模式(默认true)
   enable-self-preservation: true
