#基础配置
spring:
 application:
    name: eureka-client
server:
 port: 8080

#logging.config=classpath:log4j.xml
logging:
  config: classpath:log4j2.xml

#注册中心eureka
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8002/eureka/

#actuator
management:
 endpoints:
  web:
   exposure:
     include: "*"
