#基础配置
spring:
 application:
  name: server-gateway

server:
 port: 80

#注册中心
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8002/eureka/

#serviceId路由配置
zuul:
 routes:
  eureka-client:
   path: /service/**
   serviceId: eureka-client
#禁用默认错误处理
 SendErrorFilter:
  error:
   disable: true

#熔断超时 hystrix.command.<default/serviceId>.execution.isolation.thread.timeoutInMilliseconds
hystrix:
 command:
  default:
   execution:
    isolation:
     thread:
      timeoutInMilliseconds: 25000

#ribbon超时设置
ribbon:
 ReadTimeout: 5000
 ConnectTimeout: 5000

#url路由配置
#zuul.routes.eureka-client.path=/service/**
#zuul.routes.eureka-client.url=http://localhost:8080/
#zuul.host.connect-timeout-millis=5000
